apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- secrets.yaml
- virtual-service.yaml

namespace: staging

images:
- name: testing-apps
  newName: asia-southeast1-docker.pkg.dev/sandbox-wahyu-anggana/kci-dev/testing-apps
  newTag: 86c4f9f
