apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- virtual-service.yaml

namespace: ragil

images:
- name: ragilarfan/golangechov2
  newName: asia-southeast1-docker.pkg.dev/sandbox-wahyu-anggana/kci-dev/testing-apps
  newTag: v2
- name: testing-apps
  newName: asia-southeast1-docker.pkg.dev/sandbox-wahyu-anggana/kci-dev/testing-apps
  newTag: dedb6e4
